services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: varyshop/vonavky-web:latest
    ports:
      - "4321:4321"
    depends_on:
      - api
    environment:
      - PUBLIC_API_URL=http://api:3000

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: varyshop/vonavky-api:latest
    ports:
      - "4322:3000"
    env_file:
      - api/.env
    environment:
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:8080,https://vonavky.varyshop.eu
