services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        PUBLIC_API_URL: https://vonavky-api.varyshop.eu
    image: varyshop/vonavky-web:latest
    ports:
      - "4321:4321"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: varyshop/vonavky-api:latest
    ports:
      - "4322:3000"
    env_file:
      - api/.env
    environment:
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:8080,https://vonavky.varyshop.eu
